### ISSUE TITLE
Doesn't work with Appimage

### ISSUE THREAD

**Issue by staniki** [hezral/clips#18] opened 2021-09-17 07:31 UTC
I'm using the LibreWolf web browser as an Appimage, and Clips doesn't work with it :(

**Comment by hezral** [comment] 2021-09-17 11:29
can you explain what exactly doesn't work?

**Comment by staniki** [comment] 2021-09-17 11:59
The copied text from the LW appimage is not shown in Clips

**Comment by hezral** [comment] 2021-09-17 13:21
it seems to be working on my end. 

https://user-images.githubusercontent.com/762735/133789391-eb1427cb-8b9f-43fc-aee9-146807403a2a.mp4

**Comment by hezral** [comment] 2021-09-20 13:48
Did you confirm again?

**Comment by staniki** [comment] 2021-09-21 10:47
Hm..very strange, today I updated the application to the latest version 1.0.3 and still Clips does not copy from the DC :( I even tried to reinstall the program - nothing.
In addition, Clips is not called for me by the Command (Super) + Ctrl + C.

**Comment by hezral** [comment] 2021-09-21 11:31
the shortcut needs to be setup manually due to the sandbox permissions. You can follow the instructions in https://github.com/hezral/clips/issues/11

I'm not sure why its not working for you.. can you help to run clips from the terminal?

flatpak run com.github.hezral.clips

and try to copy something from the LW browser. 
then see what is shown in the terminal. copy the output and share it here. 

thanks.

**Comment by staniki** [comment] 2021-09-21 11:35
2021-09-21 14:34:29.349098 startup
Gtk-Message: 14:34:29.405: Failed to load module "canberra-gtk-module"

**Comment by hezral** [comment] 2021-09-21 11:58
hmm there's no error :/

leave it open and see if anything else shows up. 

I will try on another machine to see if i can reproduce the issue

**Comment by hezral** [comment] 2021-09-21 14:40
Just tested on another machine and it works. 
I got the LW appimage from here https://gitlab.com/librewolf-community/browser/appimage/-/releases. Are you getting it from there as well?

**Comment by hezral** [comment] 2021-10-15 09:35
closing this as can't reproduce

**Closed by hezral** 2021-10-15 09:35 UTC
